# Conclusion {-}

We started with a naive implementation of Lempel Ziv Welch, and our goal was to optimize it for DNA. Although we were not able to achieve as high of a compression ratio as other algorithms in literature and professional DNA compresion tools, we were able to make a very fast algorithm that can do better than a 4.0 compression ratio on large files. There is a trade off when it comes to choosing a compression algorithm, with speed and space. If you needed to compress DNA files as small as possible, you should use the professional tools or one of the algorithms proposed in other research papers. If you want to compress DNA very quickly and you are okay with a moderate compression ratio, than you should use the Four to One implementation which we discussed previously. If you want something that is in between, with a good compression ratio and fast compression time, the results in Chapter 3 tell us that the Three Stream implementation of LZW would work very well for large files.

The concept of an indexed, Direct Map dictionary is one that could prove useful for other applications. Further research could be used to apply a similar idea to a different algorithm, one more suited to the redundancies present in DNA. In other words, could we take one of the research papers discussed in Section \@ref(related-work) and apply the idea of the Direct Map to the algorithm presented in it? This could also be useful in other areas of compression in which the workload has a limited number of characters like with DNA. The usage of `pext` is also worth noting. Because of the 2 bit encoding possible for DNA sequences, we can create an index for a string of DNA very quickly. This, combined with the Direct Map Dictionary, allows for the Direct Map Dictionary to have dictionary accesses that are almost as fast as array accesses.

The Four to One implementation, another use of `pext`, is also notable. The Four to One implementation is extremely fast, and could also be useful for other compression applications where there are fewer characters than the encoding scheme accounts for (bytes can be used to store 256 different values, but only 4 are used for DNA). 

Overall, our thesis has produced a few notable implementations of LZW, created a Direct Map Dictionary data structure which has high potential for other compression applications, and shown the relevance of `pext` in optimizing compression algorithms.
