---
title: 'Optimizing Lempel-Ziv-Welch for DNA Compression'
author: 'Caden Corontzos'
date: 'May 2023'
institution: 'Reed College'
division: 'Mathematical and Natural Sciences'
advisor: 'Eitan Frachtenberg'

department: 'Computer Science'
degree: 'Bachelor of Arts'
knit: bookdown::render_book
site: bookdown::bookdown_site

header-includes:
    - \usepackage{setspace}\onehalfspacing
    - \usepackage[edges]{forest}
    - \usepackage{tikz}

params:
  'Install needed packages for {thesisdown}': True
  

output:
  thesisdown::thesis_pdf: 
    extra_dependencies: ['forest', 'tikz']

abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "00-abstract.Rmd")), collapse = "\n  ")`
acknowledgements: |
  Thank you to Eitan Frachtenberg, who helped me constantly throughout the whole year writing this. I never thought thesising would be so much fun, and I hope you enjoyed it as much as I did.

  Thanks also to all the other staff and faculty who helped me through my four years at Reed. Thank you to B Hunter, who was enormous help to me in getting jobs and opportunites throughout my time here. Thank you also to David Ramirez, whose advice and mentorship I am always grateful for. 

  Thank you to my family for supporting me, especially my parents, and thank you to all the wonderful people I met at Reed. I have enjoyed this part of my life immensely, and I am excited to see what is next.
#dedication: |
#  You can have a dedication here if you wish. 
#preface: |
#  ex
abbreviations:
  LZW: Lempel-Ziv-Welch
  RLE: Run Length Encoding
  EOF: End of file
  DNA: Deoxyribonucleic acid

bibliography: bib/thesis.bib

csl: csl/apa.csl
lot: true
lof: true
---


```{r include_packages, include=FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.
if (!require(remotes)) {
  if (params$`Install needed packages for {thesisdown}`) {
    install.packages("remotes", repos = "https://cran.rstudio.com")
  } else {
    stop(
      paste('You need to run install.packages("remotes")",
            "first in the Console.')
    )
  }
}
if (!require(thesisdown)) {
  if (params$`Install needed packages for {thesisdown}`) {
    remotes::install_github("ismayc/thesisdown")
  } else {
    stop(
      paste(
        "You need to run",
        'remotes::install_github("ismayc/thesisdown")',
        "first in the Console."
      )
    )
  }
}
if (!require(dplyr)) {
  if (params$`Install needed packages for {thesisdown}`) {
    install.packages("dplyr", repos = "https://cran.rstudio.com")
  } else {
    stop(
      paste(
        'You need to run install.packages("dplyr")',
        "first in the Console."
      )
    )
  }
}
if (!require(ggplot2)) {
  if (params$`Install needed packages for {thesisdown}`) {
    install.packages("ggplot2", repos = "https://cran.rstudio.com")
  } else {
    stop(
      paste(
        'You need to run install.packages("ggplot2")',
        "first in the Console."
      )
    )
  }
}
if (!require(bookdown)) {
  if (params$`Install needed packages for {thesisdown}`) {
    install.packages("bookdown", repos = "https://cran.rstudio.com")
  } else {
    stop(
      paste(
        'You need to run install.packages("bookdown")',
        "first in the Console."
      )
    )
  }
}

if (!require(patchwork)) {
  if (params$`Install needed packages for {thesisdown}`) {
    install.packages("patchwork", repos = "https://cran.rstudio.com")
  } else {
    stop(
      paste(
        'You need to run install.packages("patchwork")',
        "first in the Console."
      )
    )
  }
}

if (!require(tidyr)) {
  if (params$`Install needed packages for {thesisdown}`) {
    install.packages("tidyr", repos = "https://cran.rstudio.com")
  } else {
    stop(
      paste(
        'You need to run install.packages("tidyr")',
        "first in the Console."
      )
    )
  }
}

options(scipen=999)
library(tidyr)
library(dplyr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(patchwork)
library(thesisdown)
if (!require(DiagrammeR)) {
  install.packages("DiagrammeR")
}
library(DiagrammeR)
# Set how wide the R output will go
options(width = 70)
```



```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "00--prelim.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "00-abstract.Rmd")}

```

