name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "lzwcpp/**"
  pull_request:
    branches: [ "main" ]
    
defaults:
  run:
    shell: bash
    working-directory: lzwcpp

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: make test 
    - name: lzw tests
      run: ./test_lzw && ./test_three_stream_lzw 
    - name: bito tests
      run: ./test_bitio
    - name: std dict test
      run: ./dictionary/test_std_dict
    - name: direct dict test
      run: ./dictionary/test_direct_map
    - name: mult dict tests
      run: ./dictionary/test_mult_std_dict
    - name: make docs
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: 'lzwcpp'
        doxyfile-path: 'lzwcpp/doxygen.config'
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
